### ISSUE TITLE
Unable to track runs with docker-compose due to 'can't reach database server error'

### ISSUE THREAD

**Issue by jfy133** [AugustDev/nf-shard#21]
I've just tried 'blindly' following the method 1 section here:

![image](https://github.com/AugustDev/nf-shard/assets/17950287/e02a3df2-d876-4b01-934a-71d15c7591a4)

however while the dashboard loads, the console log repeatedly prints

```
nextjs_1    |  ⨯ PrismaClientInitializationError: 
nextjs_1    | Invalid `prisma.workflow.findMany()` invocation:
nextjs_1    | 
nextjs_1    | 
nextjs_1    | Can't reach database server at `localhost`:`5432`
nextjs_1    | 
nextjs_1    | Please make sure your database server is running at `localhost`:`5432`.
nextjs_1    |     at wn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:7003)
nextjs_1    |     at wn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6119)
nextjs_1    |     at wn.request (/app/node_modules/@prisma/client/runtime/library.js:123:5839)
nextjs_1    |     at async l (/app/node_modules/@prisma/client/runtime/library.js:128:9763)
nextjs_1    |     at async d (/app/build/server/chunks/901.js:1:870)
nextjs_1    |     at async u (/app/build/server/app/api/search/route.js:1:533)
nextjs_1    |     at async /app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:1:45643 {
nextjs_1    |   clientVersion: '5.3.1',
nextjs_1    |   errorCode: undefined
nextjs_1    | }
```
And the nextflow.log reporsts

```
Sept-26 10:52:43.482 [main] DEBUG nextflow.cli.Launcher - Operation aborted
nextflow.exception.AbortOperationException: Unexpected response for request http://172.18.0.3:3000/api/trace/UxbRUq_leIlshop9/begin
	at io.seqera.tower.plugin.TowerClient.onFlowBegin(TowerClient.groovy:358)
	at nextflow.Session$_notifyFlowBegin_closure22.doCall(Session.groovy:1050)
	at nextflow.Session$_notifyFlowBegin_closure22.call(Session.groovy)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2357)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2342)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2383)
	at nextflow.Session.notifyFlowBegin(Session.groovy:1050)
	at nextflow.Session.fireDataflowNetwork(Session.groovy:460)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:228)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:130)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:368)
	at nextflow.cli.Launcher.run(Launcher.groovy:494)
	at nextflow.cli.Launcher.main(Launcher.groovy:653)
```

I have a feeling I am missing something... I notice there is a mangled sentence [here](https://github.com/AugustDev/nf-shard/blob/186517a58f80e9c7013a8462f2d10aaf58265a33/README.md?plain=1#L11) about PostgreSQL... could I be missing a dependency not included within the docker image(s) used by `docker-compose`?

**Comment by gluonfield** [comment]
Sorry about that @jfy133, I had env variable left in .env file which was not compatible with docker. Now [adjusted](https://github.com/AugustDev/nf-shard/commit/7cc85239c099bdd882b94e35575f4fc99210a9d2). To fix this you should either pull latest changes or update .env file with 


```
POSTGRES_URI=postgresql://postgres:yourpassword@postgres:5432/postgres?schema=public
```

**Comment by jfy133** [comment]
Pulling worked, thanks @AugustDev !

![image](https://github.com/AugustDev/nf-shard/assets/17950287/aae9a466-5278-46e6-997b-46d1c92b69b0)
